FROM jenkins/jenkins

USER root

# Install Ansible
# RUN apt-get update && apt-get install python3-pip -y && \
#     pip3 install ansible --upgrade

# Install Docker

RUN apt-get update && \
apt-get -y install apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common && \
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable" && \
apt-get update && \
apt-get -y install docker-ce

RUN usermod -aG docker jenkins

RUN chmod 777 /var/run/docker.sock

USER jenkins
